### ISSUE TITLE
TreeAssist 1.8.x

### ISSUE THREAD

**Issue by PureAlts** [slipcor/TreeAssist#14]
`Could not pass event BlockBreakEvent to TreeAssist v5.10.36
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at net.minecraft.server.v1_8_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at net.minecraft.server.v1_8_R1.PlayerInteractManager.a(PlayerInteractManager.java:215) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:602) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at net.minecraft.server.v1_8_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at net.minecraft.server.v1_8_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:748) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:320) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:686) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:589) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/material/Sapling
	at me.itsatacoshop247.TreeAssist.trees.OakTree.replaceSapling(OakTree.java:221) ~[?:?]
	at me.itsatacoshop247.TreeAssist.trees.OakTree.handleSaplingReplace(OakTree.java:182) ~[?:?]
	at me.itsatacoshop247.TreeAssist.trees.BaseTree.maybeReplant(BaseTree.java:472) ~[?:?]
	at me.itsatacoshop247.TreeAssist.trees.BaseTree.calculate(BaseTree.java:374) ~[?:?]
	at me.itsatacoshop247.TreeAssist.TreeAssistBlockListener.onBlockBreak(TreeAssistBlockListener.java:159) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	... 16 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.material.Sapling
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
	at me.itsatacoshop247.TreeAssist.trees.OakTree.replaceSapling(OakTree.java:221) ~[?:?]
	at me.itsatacoshop247.TreeAssist.trees.OakTree.handleSaplingReplace(OakTree.java:182) ~[?:?]
	at me.itsatacoshop247.TreeAssist.trees.BaseTree.maybeReplant(BaseTree.java:472) ~[?:?]
	at me.itsatacoshop247.TreeAssist.trees.BaseTree.calculate(BaseTree.java:374) ~[?:?]
	at me.itsatacoshop247.TreeAssist.TreeAssistBlockListener.onBlockBreak(TreeAssistBlockListener.java:159) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	... 16 more
[22:40:07 ERROR]: Could not pass event BlockBreakEvent to TreeAssist v5.10.36
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at net.minecraft.server.v1_8_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at net.minecraft.server.v1_8_R1.PlayerInteractManager.a(PlayerInteractManager.java:215) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:602) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at net.minecraft.server.v1_8_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at net.minecraft.server.v1_8_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:748) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:320) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:686) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:589) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/material/Sapling
	at me.itsatacoshop247.TreeAssist.trees.OakTree.replaceSapling(OakTree.java:221) ~[?:?]
	at me.itsatacoshop247.TreeAssist.trees.OakTree.handleSaplingReplace(OakTree.java:182) ~[?:?]
	at me.itsatacoshop247.TreeAssist.trees.BaseTree.maybeReplant(BaseTree.java:472) ~[?:?]
	at me.itsatacoshop247.TreeAssist.trees.BaseTree.calculate(BaseTree.java:374) ~[?:?]
	at me.itsatacoshop247.TreeAssist.TreeAssistBlockListener.onBlockBreak(TreeAssistBlockListener.java:159) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	... 16 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.material.Sapling
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
	at me.itsatacoshop247.TreeAssist.trees.OakTree.replaceSapling(OakTree.java:221) ~[?:?]
	at me.itsatacoshop247.TreeAssist.trees.OakTree.handleSaplingReplace(OakTree.java:182) ~[?:?]
	at me.itsatacoshop247.TreeAssist.trees.BaseTree.maybeReplant(BaseTree.java:472) ~[?:?]
	at me.itsatacoshop247.TreeAssist.trees.BaseTree.calculate(BaseTree.java:374) ~[?:?]
	at me.itsatacoshop247.TreeAssist.TreeAssistBlockListener.onBlockBreak(TreeAssistBlockListener.java:159) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
	... 16 more
`

**Comment by slipcor** [comment]
The version of TreeAssist you use only works on 1.11 - please use the appropriate version as stated here (and on spigot)

http://slipcor.net/index.php?page=plugins
