### ISSUE TITLE
Console Error Spam + Lag

### ISSUE THREAD

**Issue by Faicu** [slipcor/TreeAssist#16]
Sometimes, in my console starts a spam and a lag too.
Error:
[22:01:47] [Server thread/WARN]: [TreeAssist] Task #574135 for TreeAssist v5.10.36 generated an exception
java.lang.NoSuchMethodError: com.gmail.nossr50.config.experience.ExperienceConfig.getWoodcuttingTreeXP(Lorg/bukkit/TreeSpecies;)I
    at me.itsatacoshop247.TreeAssist.core.Utils.mcMMOaddExp(Utils.java:530) ~[?:?]
    at me.itsatacoshop247.TreeAssist.trees.BaseTree.breakBlock(BaseTree.java:544) ~[?:?]
    at me.itsatacoshop247.TreeAssist.trees.BaseTree.access$000(BaseTree.java:24) ~[?:?]
    at me.itsatacoshop247.TreeAssist.trees.BaseTree$1InstantRunner.run(BaseTree.java:878) ~[?:?]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-8cbfc85-202da97]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [server.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [server.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-8cbfc85-202da97]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-8cbfc85-202da97]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
I have the latest mcmmo version at this moment + Spigot(latest) 1.12.

**Comment by slipcor** [comment]
well you might want to disable the mcMMO hook for the moment, I will have to look into what they changed, I will try to fix it next week

**Comment by slipcor** [comment]
Try this :) https://ci2.craftyn.com/job/TreeAssist/lastSuccessfulBuild/artifact/target/TreeAssist.jar
