### ISSUE TITLE
1.12 support?

### ISSUE THREAD

**Issue by k-jiang** [slipcor/TreeAssist#17]
1.12 is out for a while. Any plan on supporting it please?

```
[00:20:18 ERROR]: Could not pass event BlockBreakEvent to TreeAssist v5.10.36
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-survival.jar:git-Spigot-cd6ba67-a7d074c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-survival.jar:git-Spigot-cd6ba67-a7d074c]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-survival.jar:git-Spigot-cd6ba67-a7d074c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-survival.jar:git-Spigot-cd6ba67-a7d074c]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:289) [spigot-survival.jar:git-Spigot-cd6ba67-a7d074c]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:216) [spigot-survival.jar:git-Spigot-cd6ba67-a7d074c]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:882) [spigot-survival.jar:git-Spigot-cd6ba67-a7d074c]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) [spigot-survival.jar:git-Spigot-cd6ba67-a7d074c]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) [spigot-survival.jar:git-Spigot-cd6ba67-a7d074c]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-survival.jar:git-Spigot-cd6ba67-a7d074c]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-survival.jar:git-Spigot-cd6ba67-a7d074c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-survival.jar:git-Spigot-cd6ba67-a7d074c]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-survival.jar:git-Spigot-cd6ba67-a7d074c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-survival.jar:git-Spigot-cd6ba67-a7d074c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-survival.jar:git-Spigot-cd6ba67-a7d074c]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
        at me.itsatacoshop247.TreeAssist.trees.SpruceTree.calculate(SpruceTree.java:28) ~[?:?]
        at me.itsatacoshop247.TreeAssist.trees.BaseTree.removeLater(BaseTree.java:769) ~[?:?]
        at me.itsatacoshop247.TreeAssist.trees.BaseTree.calculate(BaseTree.java:396) ~[?:?]
        at me.itsatacoshop247.TreeAssist.TreeAssistBlockListener.onBlockBreak(TreeAssistBlockListener.java:159) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor351.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-survival.jar:git-Spigot-cd6ba67-a7d074c]
        ... 17 more
>version
[00:30:57 INFO]: This server is running CraftBukkit version git-Spigot-cd6ba67-a7d074c (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
[00:30:57 INFO]: Checking version, please wait...
[00:30:59 INFO]: You are 1 version(s) behind
```

Thank you for your effort!

**Comment by slipcor** [comment]
This has nothing to do with 1.12, I already fixed this, I was just waiting for feedback but got none, so please try this aaaaaand tell me.... If I do not  get answers or bug reports I will release this today. It has been fixed for over a week now:

https://ci2.craftyn.com/job/TreeAssist/lastSuccessfulBuild/artifact/target/TreeAssist.jar

**Comment by slipcor** [comment]
and just to clarify, 1.12 is still not the default recommended latest build. at least for my buildtools version :P anyways, it has to work, they did not change anything I know of, about stuff that TreeAssist cares about

**Comment by k-jiang** [comment]
Well I just tested it.
Issue 1: This was a 2x2 Spruce. Chop it and now becomes a 1x1.
![2017-06-17_13 38 17](https://user-images.githubusercontent.com/6910542/27254992-5e045a90-5362-11e7-9e25-8e59224f0672.png)

Issue 2: It Doesn't work well on tree branches. I don't believe it has some thing to do with the above exception, but more like a "traditional" issue lol
![2017-06-17_13 46 42](https://user-images.githubusercontent.com/6910542/27255041-9c99efda-5363-11e7-8c8c-4d1fc71d611f.png)
![2017-06-17_13 46 54](https://user-images.githubusercontent.com/6910542/27255042-a1eda5a8-5363-11e7-86da-901e4cb912e1.png)

So far that's all I found.

**Comment by slipcor** [comment]
wait is this overhangin thing a branch? that looks WAY out of place... dude that is way too crazy xD I will not catch this, this is like 10 blocks away from the main trunk :/

about spruce, I have heard reports of that, but I could not replicate this, can you give me a better picture of this? I might try to fix this tomorrow but I am not sure if I can find time

**Comment by k-jiang** [comment]
Before:
![image](https://user-images.githubusercontent.com/6910542/27256422-5e4f7898-5382-11e7-9aa4-3fc9779ccc4c.png)
After:
![image](https://user-images.githubusercontent.com/6910542/27256424-62b253f6-5382-11e7-9dba-8e7bed28103c.png)
Chopped with diamond axe.

**Comment by slipcor** [comment]
Thanks for the report, it took me some time to find this :O It has been fixed, sorry for the inconvenience :)

https://ci2.craftyn.com/job/TreeAssist/lastSuccessfulBuild/artifact/target/TreeAssist.jar

Or on Spigot, I just released it ^^

**Comment by k-jiang** [comment]
Good job! Thank you for you effort.
