### ISSUE TITLE
Compatibility with PaperSpigot

### ISSUE THREAD

**Issue by k-jiang** [slipcor/TreeAssist#19]
Paper 1.12.1 build 1183 https://ci.destroystokyo.com/job/PaperSpigot/
TreeAssist 5.11.48
I have switched to Paper since 1.12 due to mysterious lagging, dk if the original Spigot has the same issue.
```
[22:50:09 ERROR]: Could not pass event BlockBreakEvent to TreeAssist v5.11.48
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.12.1.jar:git-Paper-1183]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.1.jar:git-Paper-1183]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.1.jar:git-Paper-1183]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[patched_1.12.1.jar:git-Paper-1183]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[patched_1.12.1.jar:git-Paper-1183]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:290) ~[patched_1.12.1.jar:git-Paper-1183]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:217) ~[patched_1.12.1.jar:git-Paper-1183]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:886) ~[patched_1.12.1.jar:git-Paper-1183]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.12.1.jar:git-Paper-1183]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.12.1.jar:git-Paper-1183]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.1.jar:git-Paper-1183]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.1.jar:git-Paper-1183]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.1.jar:git-Paper-1183]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [patched_1.12.1.jar:git-Paper-1183]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.1.jar:git-Paper-1183]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.1.jar:git-Paper-1183]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
        at me.itsatacoshop247.TreeAssist.trees.wood.JungleBigTree.calculate(JungleBigTree.java:23) ~[TreeAssist-5.11.48-CB1.12.jar:?]
        at me.itsatacoshop247.TreeAssist.trees.AbstractGenericTree.removeLater(AbstractGenericTree.java:786) ~[TreeAssist-5.11.48-CB1.12.jar:?]
        at me.itsatacoshop247.TreeAssist.trees.AbstractGenericTree.calculate(AbstractGenericTree.java:415) ~[TreeAssist-5.11.48-CB1.12.jar:?]
        at me.itsatacoshop247.TreeAssist.TreeAssistBlockListener.onBlockBreak(TreeAssistBlockListener.java:146) ~[TreeAssist-5.11.48-CB1.12.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor632.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.12.1.jar:git-Paper-1183]
        ... 18 more

```

**Comment by slipcor** [comment]
Can you show me a tree for which this is happening? Version #48 should be safe from this kind of error - I cannot imagine that this is specific to the server version, or a server update... If this is triggered for all big jungle trees, I am really confused as to why this can be happening oO

So either you are trying to break an invalid tree (or a house?) - or I am missing something on my end.

I will look into this tomorrow!

**Comment by k-jiang** [comment]
I saw this showed up on the console occasionally. Don't know what happened. I have tried to chop down some trees and wooden houses but with no luck.

I will post here if I see something in the future.

**Comment by zPorto** [comment]
Having the same problem with PaperSpigot 1.8
Using TreeAssist v5.9.12

**Comment by ArtNRG** [comment]
Same problem: https://pastebin.com/4bQSGd9f

**Comment by slipcor** [comment]
technically not the same problem, it's another tree now - should be fixed in a minute ;)
