### ISSUE TITLE
when i cut the tree the server shell show errors

### ISSUE THREAD

**Issue by huzion** [slipcor/TreeAssist#37]
OS: debian9 x64
server: paper-652.jar （paperspigot 1.13.2）
plugins:

AConomy
AntiCreeper
AuthMe
Coins
EliteMobs
EssentialsX
EXPBank
LockettePro
mcMMO
ProtocolLib
SkinsRestorer
QuickShop
TreeAssist
Vault
VeinMiner
Residence
WorldEdit
WorldGuard

--------------------------------------------errors---------------------------------------------

[00:08:39 ERROR]: Could not pass event LeavesDecayEvent to TreeAssist v6.0.77
java.lang.NullPointerException: null
        at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.itemCausesDrops(CraftBlock.java:531) ~[patched_1.13.2.jar:git-Paper-652]
        at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.breakNaturally(CraftBlock.java:550) ~[patched_1.13.2.jar:git-Paper-652]
        at me.itsatacoshop247.TreeAssist.core.Utils.breakBlock(Utils.java:735) ~[?:?]
        at me.itsatacoshop247.TreeAssist.core.Utils.breakBlock(Utils.java:708) ~[?:?]
        at me.itsatacoshop247.TreeAssist.TreeAssistBlockListener.breakRadiusLeaves(TreeAssistBlockListener.java:243) ~[?:?]
        at me.itsatacoshop247.TreeAssist.TreeAssistBlockListener.onLeavesDecay(TreeAssistBlockListener.java:54) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor672.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-652]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-652]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-652]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-652]
        at net.minecraft.server.v1_13_R2.BlockLeaves.b(BlockLeaves.java:27) ~[patched_1.13.2.jar:git-Paper-652]
        at net.minecraft.server.v1_13_R2.IBlockData.b(IBlockData.java:232) ~[patched_1.13.2.jar:git-Paper-652]
        at net.minecraft.server.v1_13_R2.WorldServer.n_(WorldServer.java:552) ~[patched_1.13.2.jar:git-Paper-652]
        at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:301) ~[patched_1.13.2.jar:git-Paper-652]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1091) ~[patched_1.13.2.jar:git-Paper-652]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-652]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-652]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-652]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

**Comment by slipcor** [comment]
Please try this build, should be fixed :)

https://ci2.craftyn.com/job/TreeAssist/lastSuccessfulBuild/artifact/target/TreeAssist.jar

**Comment by huzion** [comment]
> Please try this build, should be fixed :)
> 
> https://ci2.craftyn.com/job/TreeAssist/lastSuccessfulBuild/artifact/target/TreeAssist.jar

it works!  thx  :)
