### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Typhome** [slipcor/TreeAssist#5]
```[21:59:45] [Server thread/WARN]: [TreeAssist] Task #135533 for TreeAssist v5.10.18 generated an exception
java.lang.NullPointerException
   at me.itsatacoshop247.TreeAssist.trees.BaseTree.breakBlock(BaseTree.java:538) ~[?:?]
   at me.itsatacoshop247.TreeAssist.trees.BaseTree.access$000(BaseTree.java:24) ~[?:?]
   at me.itsatacoshop247.TreeAssist.trees.BaseTree$1CleanRunner.run(BaseTree.java:888) ~[?:?]
   at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
   at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
   at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:728) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
   at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
   at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
   at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
   at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]```

Spigot version 1.10.2
https://i.gyazo.com/3054d5a96cb48c125269fd16fcd5d1c5.png

**Comment by slipcor** [comment]
That was bound to happen :/ sadly this shows that some clients will still have "unbroken" logs as this still might fail... Maybe not, though. We will see :)

https://ci2.craftyn.com/job/TreeAssist/

Please use with caution, I have untested changes about the block list - the list that tries to make sure no user placed blocks trigger an auto removal ;)

I will be able to test this in about 6 hours.

**Comment by Typhome** [comment]
Still added v5.10.20 to my public server (average +30 online players) and no errors in console at this moment.
