### ISSUE TITLE
Warn in console

### ISSUE THREAD

**Issue by Floodo** [slipcor/TreeAssist#96]
Hello :) I just started server (Paper 1.19) and than this warn shows up in console.

[18:01:22 INFO]: [TreeAssist] Loading TreeAssist v7.3.48
[18:01:22 INFO]: [TreeAssist] Loading main config file: \config.yml
[18:01:22 WARN]: [TreeAssist] config.yml: Plugins.AureliumPerBlock expects double, integer given!
[18:01:22 WARN]: [TreeAssist] config.yml: Plugins.AureliumPerTree expects double, integer given!
[18:01:22 WARN]: [TreeAssist] Invalid Material in TreeConfig default.yml - Node Natural Blocks entry invalid: minecraft:pink_petals
[18:01:22 WARN]: [TreeAssist] No valid material minecraft:cherry_leaves in node Blocks.Custom Drops.Items.minecraft:cherry_leaves
[18:01:22 WARN]: [TreeAssist] No valid node: Blocks.Custom Drops.Items.minecraft:cherry_leaves
[18:01:22 WARN]: [TreeAssist] Invalid Material in TreeConfig cherry.yml - Node Blocks.Materials entry invalid: minecraft:cherry_leaves
[18:01:22 WARN]: [TreeAssist] Invalid Material in TreeConfig cherry.yml - Node Trunk.Materials entry invalid: minecraft:cherry_log
[18:01:22 WARN]: [TreeAssist] Invalid Material in TreeConfig cherry.yml - Node Trunk.Materials entry invalid: minecraft:stripped_cherry_log
[18:01:22 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.Material.equals(Object)" because "replantMat" is null
[18:01:22 WARN]:        at TreeAssist (6).jar//net.slipcor.treeassist.yml.TreeConfig.load(TreeConfig.java:305)
[18:01:22 WARN]:        at TreeAssist (6).jar//net.slipcor.treeassist.discovery.TreeStructure.reloadTreeDefinitions(TreeStructure.java:894)
[18:01:22 WARN]:        at TreeAssist (6).jar//net.slipcor.treeassist.TreeAssist.reloadLists(TreeAssist.java:440)
[18:01:22 WARN]:        at TreeAssist (6).jar//net.slipcor.treeassist.TreeAssist.onLoad(TreeAssist.java:409)
[18:01:22 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:427)
[18:01:22 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:278)
[18:01:22 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1122)
[18:01:22 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303)
[18:01:22 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by slipcor** [comment]
If this still is a problem, remove the cherry.yml - but these are warnings and do not cause any other issues.
